name: Build Telegram bot Image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: setup qemu
        uses: docker/setup-qemu-action@v3
      -
        name: checkout yt-dlp-telgram-bot
        uses: actions/checkout@v6
        with:
          repository: nonoo/yt-dlp-telegram-bot
          ref: main
          path: container
      -
        name: container registry login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v6
        with:
          context: container
          platforms:
            - linux/amd64
            - linux/arm64
            - linux/arm64/v8
          file: container/Dockerfile
          tags: ghcr.io/sudhegan/yt-dlp-telgram-bot:latest
